---
title: Calendrier
---
flowchart LR
    %% Defining Actors
    subgraph "Utilisateurs"
        direction LR
        Student(("Enfant"))
        Volunteer(("Bénévole"))
        User(("Utilisateur"))
        %% Inheritance
        Student --> User
        Volunteer --> User
    end

    %% Defining Use Cases
    subgraph "Use Cases"
        direction TB
        UC_NavigateCalendar(["Naviguer dans le calendrier mensuel"])
        UC_ReturnToCurrentMonth(["Retour au mois en cours (bouton « Aujourd'hui »)"])
        UC_SelectDay(["Sélectionner un jour (filtre)"])
        UC_DeselectDay(["Annuler la sélection d'un jour (afficher tous les événements)"])
        UC_ViewEventDetails(["Afficher les détails d'un événement"])
        UC_ScheduleEvent(["Planifier un nouvel événement"])
        UC_EditEvent(["Modifier un événement"])
        UC_DeleteEvent(["Supprimer un événement"])
        UC_ViewAppointmentDetails(["Afficher les détails d'un rendez-vous"])
        UC_ScheduleAppointment(["Planifier un nouveau rendez-vous"])
        UC_EditAppointment(["Modifier un rendez-vous"])
        UC_DeleteAppointment(["Supprimer un rendez-vous"])
    end

    %% Actor to Use Case Relationships
    User --> UC_ScheduleEvent
    User --> UC_ViewEventDetails
    Volunteer --> UC_ScheduleAppointment
    User --> UC_ViewAppointmentDetails
    User --> UC_NavigateCalendar
    User --> UC_ReturnToCurrentMonth
    User --> UC_SelectDay

    %% Intra Use Case Relationships
    UC_SelectDay -->|<< extend >>| UC_DeselectDay
    UC_ReturnToCurrentMonth -->|<< include >>| UC_DeselectDay
    UC_ViewEventDetails -->|<< extend >>| UC_EditEvent
    UC_ViewEventDetails -->|<< extend >>| UC_DeleteEvent
    UC_ViewAppointmentDetails -->|<< extend >>| UC_EditAppointment
    UC_ViewAppointmentDetails -->|<< extend >>| UC_DeleteAppointment

    %% Critical Paths
    linkStyle 2,3,4,5 stroke:indigo,stroke-width:3px;